"""The Python half of encryptor's interop test.

Encryptor.PythonInteropTest (test/encryptor/interop/python_interop_test.exs)
drives this script; it is not meant to be run on its own. It takes a mode and
a work directory the test wrote:

    python interop.py decrypt DIR   # Python reads the messages encryptor wrote
    python interop.py encrypt DIR   # Python writes messages for encryptor to read

DIR holds `key.bin` (the 32-byte test wrapping key, generated by the test for
this run and never committed), `cases.json` (the cases and the non-secret
parameters) and, for decrypt, one `<id>.ct` and one `<id>.pt` per case. The
script writes `results.json` and, for encrypt, one `<id>.ct` per case.

Nothing it prints or writes carries key material or plaintext: a case's result
is an outcome word, and for an error the exception's class and message.
"""

import io
import json
import os
import sys

import aws_encryption_sdk
from aws_encryption_sdk import CommitmentPolicy
from aws_encryption_sdk.identifiers import AlgorithmSuite
from aws_encryption_sdk.internal.formatting.deserialize import deserialize_header
from aws_cryptographic_material_providers.mpl import AwsCryptographicMaterialProviders
from aws_cryptographic_material_providers.mpl.config import MaterialProvidersConfig
from aws_cryptographic_material_providers.mpl.models import (
    AesWrappingAlg,
    CreateDefaultCryptographicMaterialsManagerInput,
    CreateRawAesKeyringInput,
    CreateRequiredEncryptionContextCMMInput,
)

SUITES = {
    0x0478: AlgorithmSuite.AES_256_GCM_HKDF_SHA512_COMMIT_KEY,
    0x0578: AlgorithmSuite.AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384,
}


def error_text(exc):
    return f"{type(exc).__module__}.{type(exc).__name__}: {exc}"[:300]


def stored_context_keys(ciphertext):
    try:
        header, _ = deserialize_header(io.BytesIO(ciphertext))
        return sorted(header.encryption_context)
    except Exception:  # the header parse is a report, never the verdict
        return None


def main(mode, work_dir):
    aws_variables = [name for name in os.environ if name.startswith("AWS_")]
    if aws_variables:
        sys.exit(f"refusing to run: {len(aws_variables)} AWS_ environment variable(s) set")

    with open(os.path.join(work_dir, "key.bin"), "rb") as key_file:
        wrapping_key = key_file.read()
    if len(wrapping_key) != 32:
        sys.exit("key.bin is not a 32-byte key")

    with open(os.path.join(work_dir, "cases.json"), encoding="utf-8") as cases_file:
        spec = json.load(cases_file)

    mpl = AwsCryptographicMaterialProviders(config=MaterialProvidersConfig())
    keyring = mpl.create_raw_aes_keyring(
        CreateRawAesKeyringInput(
            key_namespace=spec["key_namespace"],
            key_name=spec["key_name"],
            wrapping_key=wrapping_key,
            wrapping_alg=AesWrappingAlg.ALG_AES256_GCM_IV12_TAG16,
        )
    )
    default_cmm = mpl.create_default_cryptographic_materials_manager(
        CreateDefaultCryptographicMaterialsManagerInput(keyring=keyring)
    )
    client = aws_encryption_sdk.EncryptionSDKClient(
        commitment_policy=CommitmentPolicy.REQUIRE_ENCRYPT_REQUIRE_DECRYPT
    )

    def materials_manager(case):
        required = case["required_keys"]
        if not required:
            return default_cmm
        return mpl.create_required_encryption_context_cmm(
            CreateRequiredEncryptionContextCMMInput(
                required_encryption_context_keys=required, underlying_cmm=default_cmm
            )
        )

    results = {}
    for case in spec["cases"]:
        case_id = case["id"]
        context = case["encryption_context"]
        path = os.path.join(work_dir, case_id)
        result = {}
        try:
            if mode == "decrypt":
                with open(path + ".ct", "rb") as ct_file:
                    ciphertext = ct_file.read()
                with open(path + ".pt", "rb") as pt_file:
                    expected = pt_file.read()
                result["stored_context_keys"] = stored_context_keys(ciphertext)
                plaintext, header = client.decrypt(
                    source=ciphertext,
                    materials_manager=materials_manager(case),
                    encryption_context=context,
                )
                context_held = all(header.encryption_context.get(k) == v for k, v in context.items())
                if plaintext != expected:
                    result["outcome"] = "plaintext_mismatch"
                elif not context_held:
                    result["outcome"] = "context_mismatch"
                else:
                    result["outcome"] = "pass"
            else:
                with open(path + ".pt", "rb") as pt_file:
                    plaintext = pt_file.read()
                ciphertext, _ = client.encrypt(
                    source=plaintext,
                    materials_manager=materials_manager(case),
                    encryption_context=context,
                    algorithm=SUITES[case["suite"]],
                )
                with open(path + ".ct", "wb") as ct_file:
                    ct_file.write(ciphertext)
                result["outcome"] = "pass"
                result["stored_context_keys"] = stored_context_keys(ciphertext)
        except Exception as exc:  # reported per case; the test asserts on it
            result["outcome"] = "error"
            result["error"] = error_text(exc)
        results[case_id] = result
        print(f"{mode} {case_id}: {result['outcome']}")

    with open(os.path.join(work_dir, "results.json"), "w", encoding="utf-8") as out:
        json.dump(results, out, indent=2, sort_keys=True)


if __name__ == "__main__":
    if len(sys.argv) != 3 or sys.argv[1] not in ("decrypt", "encrypt"):
        sys.exit("usage: interop.py decrypt|encrypt DIR")
    main(sys.argv[1], sys.argv[2])
